version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: ai-chat-application-1113-main-frontend-1
    restart: unless-stopped
    expose:
      - "4173"
    networks:
      - saga4v_network

  main_backend:
    build:
      context: .
      dockerfile: server/Dockerfile
    container_name: ai-chat-application-1113-main-backend-1
    restart: unless-stopped
    env_file:
      - .env.production
    environment:
      - NODE_ENV=production
      - SERVER_PORT=4242
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - saga4v_network
    expose:
      - "4242"

  payment_backend:
    build:
      context: .
      dockerfile: payment-server/Dockerfile
    container_name: ai-chat-application-1113-main-payment-server-1
    restart: unless-stopped
    env_file:
      - .env.production
    environment:
      - NODE_ENV=production
      - PAYMENT_SERVER_PORT=4242
    volumes:
      - ./payment-server:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - saga4v_network
    expose:
      - "4242"

networks:
  saga4v_network:
    external: true
    name: saga4v_network