version: '3.8'

services:
  frontend:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: ai-chat-frontend
    restart: unless-stopped
    env_file: 
      - .env.production
    ports:
      - "4173:4173"
    environment:
      - NODE_ENV=production
      - VITE_API_URL=https://love.saga4v.com
      - VITE_SOCKET_URL=wss://love.saga4v.com
      - VITE_WEBSOCKET_PATH=/socket.io
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4173/ || exit 0"]
      interval: 60s
      timeout: 30s
      retries: 3
      start_period: 180s
    networks:
      - saga4v_network
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  payment:
    build:
      context: .
      dockerfile: Dockerfile.payment
    container_name: ai-chat-payment
    restart: unless-stopped
    env_file:
      - .env.production
    environment:
      - NODE_ENV=production
      - PORT=4242
      - CORS_ORIGIN=https://love.saga4v.com
      - SKIP_FIREBASE_CONFIG=true
    ports:
      - "4242:4242"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:4242/health || exit 0"]
      interval: 60s
      timeout: 30s
      retries: 3
      start_period: 120s
    networks:
      - saga4v_network
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  saga4v_network:
    external: true
    name: saga4v_network