version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - frontend
      - payment

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_ENV=production
    expose:
      - "4173"
    env_file:
      - .env.production
    environment:
      - NODE_ENV=production
      # Marquee Config
      - VITE_MARQUEE_ENABLED=true
      - VITE_MARQUEE_ANIMATION_DURATION=20000
    command: >
      sh -c "
        export PATH=/app/node_modules/.bin:$PATH &&
        npm run clean &&
        npm run build:prod &&
        npm run preview:prod
      "
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:4173 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    restart: unless-stopped

  payment:
    build:
      context: ./payment-server
      dockerfile: Dockerfile
    expose:
      - "4242"
    env_file:
      - .env.production
    environment:
      - NODE_ENV=production
    command: >
      sh -c "npm install && npm start"
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:4242"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: unless-stopped

networks:
  default:
    driver: bridge

volumes:
  payment_data:
    driver: local