version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4173:4173"
    env_file:
      - .env.production
    environment:
      - NODE_ENV=production
    command: >
      sh -c "
        npm install &&
        npm run clean &&
        npm run build:prod &&
        npm run preview:prod
      "
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:4173 || exit 0"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    restart: unless-stopped

  payment:
    build:
      context: ./payment-server
      dockerfile: Dockerfile
    ports:
      - "4242:4242"
    env_file:
      - .env.production
    environment:
      - NODE_ENV=production
    command: >
      sh -c "npm install && npm start"
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:4242"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: unless-stopped
    depends_on:
      frontend:
        condition: service_healthy

networks:
  default:
    driver: bridge

volumes:
  payment_data:
    driver: local