version: '3'

services:
  nginx:
    image: nginx:latest
    expose:
      - "80"
      - "443"
    volumes:
      - /etc/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      frontend:
        condition: service_healthy
      payment:
        condition: service_healthy
    restart: unless-stopped

  frontend:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_ENV=production
    expose:
      - "4173"
    env_file:
      - .env.production
    environment:
      # AI API Keys
      - VITE_MOONSHOT_API_KEY=${VITE_MOONSHOT_API_KEY}
      - VITE_GEMINI_API_KEY=${VITE_GEMINI_API_KEY}
      # App Config
      - NODE_ENV=production
      - VITE_API_KEY=${VITE_API_KEY}
      - VITE_API_URL=http://payment:4242
      # Firebase Config
      - VITE_FIREBASE_API_KEY=${VITE_FIREBASE_API_KEY}
      - VITE_FIREBASE_AUTH_DOMAIN=${VITE_FIREBASE_AUTH_DOMAIN}
      - VITE_FIREBASE_PROJECT_ID=${VITE_FIREBASE_PROJECT_ID}
      - VITE_FIREBASE_STORAGE_BUCKET=${VITE_FIREBASE_STORAGE_BUCKET}
      - VITE_FIREBASE_MESSAGING_SENDER_ID=${VITE_FIREBASE_MESSAGING_SENDER_ID}
      - VITE_FIREBASE_APP_ID=${VITE_FIREBASE_APP_ID}
      - VITE_FIREBASE_MEASUREMENT_ID=${VITE_FIREBASE_MEASUREMENT_ID}
      # Stripe Config
      - VITE_STRIPE_PUBLISHABLE_KEY=${VITE_STRIPE_PUBLISHABLE_KEY}
      - VITE_STRIPE_MODE=${VITE_STRIPE_MODE}
      # Marquee Config
      - VITE_MARQUEE_ENABLED=true
      - VITE_MARQUEE_ANIMATION_DURATION=20000
      - HOST=0.0.0.0
    command: >
      sh -c "
        export PATH=/app/node_modules/.bin:$PATH &&
        npm run clean &&
        npm run build:prod &&
        npm run preview:prod
      "
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:4173"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    restart: unless-stopped

  payment:
    build: 
      context: ./payment-server
      dockerfile: Dockerfile
    expose:
      - "4242"
    env_file:
      - .env.production
    environment:
      - PORT=4242
      - NODE_ENV=production
      # Stripe Config
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - VITE_STRIPE_PUBLISHABLE_KEY=${VITE_STRIPE_PUBLISHABLE_KEY}
      - VITE_STRIPE_MODE=${VITE_STRIPE_MODE}
    command: >
      sh -c "npm install && npm start"
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:4242"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: unless-stopped

networks:
  default:
    driver: bridge

volumes:
  payment_data:
    driver: local