# version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
      args:
        - VITE_FIREBASE_API_KEY=${VITE_FIREBASE_API_KEY}
        - VITE_FIREBASE_AUTH_DOMAIN=${VITE_FIREBASE_AUTH_DOMAIN}
        - VITE_FIREBASE_PROJECT_ID=${VITE_FIREBASE_PROJECT_ID}
        - VITE_FIREBASE_STORAGE_BUCKET=${VITE_FIREBASE_STORAGE_BUCKET}
        - VITE_FIREBASE_MESSAGING_SENDER_ID=${VITE_FIREBASE_MESSAGING_SENDER_ID}
        - VITE_FIREBASE_APP_ID=${VITE_FIREBASE_APP_ID}
        - VITE_FIREBASE_MEASUREMENT_ID=${VITE_FIREBASE_MEASUREMENT_ID}
        - VITE_API_URL=${VITE_API_URL}
        - VITE_APP_URL=${VITE_APP_URL}
        - VITE_PAYMENT_API_URL=${VITE_PAYMENT_API_URL}
        - VITE_SOCKET_URL=${VITE_SOCKET_URL}
        - VITE_DEFAULT_LANGUAGE=${VITE_DEFAULT_LANGUAGE}
        - VITE_SUPABASE_URL=${VITE_SUPABASE_URL}
        - VITE_SUPABASE_ANON_KEY=${VITE_SUPABASE_ANON_KEY}
        - VITE_STRIPE_PUBLISHABLE_KEY=${VITE_STRIPE_PUBLISHABLE_KEY}
        - VITE_ENABLE_STRIPE=${VITE_ENABLE_STRIPE}
        - VITE_ENABLE_PAYPAL=${VITE_ENABLE_PAYPAL}
        - VITE_ENABLE_TON=${VITE_ENABLE_TON}
        - VITE_MARQUEE_ENABLED=${VITE_MARQUEE_ENABLED}
        - VITE_MARQUEE_WEBSOCKET_URL=${VITE_MARQUEE_WEBSOCKET_URL}
        - VITE_PAYMENT_URL=${VITE_PAYMENT_URL}
        - VITE_SHOW_DEBUG_LOGS=${VITE_SHOW_DEBUG_LOGS}
        - VITE_MOONSHOT_API_KEY=${VITE_MOONSHOT_API_KEY}
        - VITE_GEMINI_API_KEY=${VITE_GEMINI_API_KEY}
        - VITE_GROK_API_KEY=${VITE_GROK_API_KEY}
        - VITE_ZHIPU_API_KEY=${VITE_ZHIPU_API_KEY}
        - VITE_OPENROUTER_API_KEY=${VITE_OPENROUTER_API_KEY}
        - VITE_OPENROUTER_SITE_URL=${VITE_OPENROUTER_SITE_URL}
        - VITE_OPENROUTER_SITE_NAME=${VITE_OPENROUTER_SITE_NAME}
    container_name: ai-chat-application-1113-main-frontend-1
    restart: unless-stopped
    expose:
      - "4173"
    networks:
      - saga4v_network
    depends_on:
      - main_backend

  main_backend:
    build:
      context: .
      dockerfile: server/Dockerfile
    container_name: ai-chat-application-1113-main-backend-1
    restart: unless-stopped
    env_file:
      - .env.production
    environment:
      - NODE_ENV=production
      - SERVER_PORT=4242
    networks:
      - saga4v_network
    expose:
      - "4242"

  payment_backend:
    build:
      context: .
      dockerfile: payment-server/Dockerfile
    container_name: ai-chat-application-1113-main-payment-server-1
    restart: unless-stopped
    env_file:
      - .env.production
    environment:
      - NODE_ENV=production
      - PAYMENT_SERVER_PORT=4242
    networks:
      - saga4v_network
    expose:
      - "4242"

networks:
  saga4v_network:
    external: true
    name: saga4v_network