version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4173:4173"
    environment:
      - NODE_ENV=production
      - VITE_API_KEY=${VITE_API_KEY}
      - VITE_MOONSHOT_API_KEY=${VITE_MOONSHOT_API_KEY}
      - VITE_GEMINI_API_KEY=${VITE_GEMINI_API_KEY}
      - VITE_STRIPE_MODE=${VITE_STRIPE_MODE}
      - VITE_STRIPE_PUBLISHABLE_KEY=${VITE_STRIPE_PUBLISHABLE_KEY}
      - VITE_FIREBASE_API_KEY=${VITE_FIREBASE_API_KEY}
      - VITE_FIREBASE_AUTH_DOMAIN=${VITE_FIREBASE_AUTH_DOMAIN}
      - VITE_FIREBASE_PROJECT_ID=${VITE_FIREBASE_PROJECT_ID}
      - VITE_FIREBASE_STORAGE_BUCKET=${VITE_FIREBASE_STORAGE_BUCKET}
      - VITE_FIREBASE_MESSAGING_SENDER_ID=${VITE_FIREBASE_MESSAGING_SENDER_ID}
      - VITE_FIREBASE_APP_ID=${VITE_FIREBASE_APP_ID}
      - VITE_FIREBASE_MEASUREMENT_ID=${VITE_FIREBASE_MEASUREMENT_ID}
    command: >
      sh -c "
        npm install &&
        npm run clean &&
        npm run build:prod &&
        npm run preview:prod
      "
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:4173 || exit 0"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    restart: unless-stopped

  payment:
    build:
      context: ./payment-server
      dockerfile: Dockerfile
    ports:
      - "4242:4242"
    environment:
      - NODE_ENV=production
      - PORT=4242
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - VITE_STRIPE_PUBLISHABLE_KEY=${VITE_STRIPE_PUBLISHABLE_KEY}
      - VITE_STRIPE_MODE=${VITE_STRIPE_MODE}
    command: >
      sh -c "
        npm install &&
        npm run clean &&
        npm run build:prod &&
        npm run server:prod
      "
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:4242"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: unless-stopped
    depends_on:
      frontend:
        condition: service_healthy

networks:
  default:
    driver: bridge

volumes:
  payment_data:
    driver: local 