# version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt/live/love.saga4v.com/fullchain.pem:/etc/nginx/ssl/fullchain.pem:ro
      - /etc/letsencrypt/live/love.saga4v.com/privkey.pem:/etc/nginx/ssl/privkey.pem:ro
    depends_on:
      frontend:
        condition: service_healthy
      payment:
        condition: service_healthy
    restart: unless-stopped

  frontend:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_ENV=production
    ports:
      - "4173:4173"
    env_file:
      - .env.production
    environment:
      # Ensure default values for all environment variables
      - VITE_MOONSHOT_API_KEY=${VITE_MOONSHOT_API_KEY:-}
      - VITE_GEMINI_API_KEY=${VITE_GEMINI_API_KEY:-}
      - NODE_ENV=production
      - VITE_API_KEY=${VITE_API_KEY:-}
      - VITE_API_URL=https://love.saga4v.com/api
      # Firebase Config with default empty strings
      - VITE_FIREBASE_API_KEY=${VITE_FIREBASE_API_KEY:-}
      - VITE_FIREBASE_AUTH_DOMAIN=${VITE_FIREBASE_AUTH_DOMAIN:-}
      - VITE_FIREBASE_PROJECT_ID=${VITE_FIREBASE_PROJECT_ID:-}
      - VITE_FIREBASE_STORAGE_BUCKET=${VITE_FIREBASE_STORAGE_BUCKET:-}
      - VITE_FIREBASE_MESSAGING_SENDER_ID=${VITE_FIREBASE_MESSAGING_SENDER_ID:-}
      - VITE_FIREBASE_APP_ID=${VITE_FIREBASE_APP_ID:-}
      - VITE_FIREBASE_MEASUREMENT_ID=${VITE_FIREBASE_MEASUREMENT_ID:-}
      # Stripe Config with default empty strings
      - VITE_STRIPE_PUBLISHABLE_KEY=${VITE_STRIPE_PUBLISHABLE_KEY:-}
      - VITE_STRIPE_MODE=live
      # Marquee Config
      - VITE_MARQUEE_ENABLED=true
      - VITE_MARQUEE_ANIMATION_DURATION=20000
      - HOST=0.0.0.0
      - VITE_USE_HTTPS=true
    command: >
      sh -c "
        export PATH=/app/node_modules/.bin:$PATH &&
        echo ' Starting Frontend Deployment...' &&
        npm run clean &&
        echo ' Building Production Assets...' &&
        npm run build:prod &&
        echo ' Listing dist contents...' &&
        ls -la dist &&
        echo ' Starting Preview Server...' &&
        npm run preview:prod
      "
    healthcheck:
      test: ["CMD-SHELL", "/healthcheck.sh"]
      interval: 30s
      timeout: 20s
      retries: 5
      start_period: 120s
    restart: unless-stopped

  payment:
    build: 
      context: ./payment-server
      dockerfile: Dockerfile
    ports:
      - "4242:4242"
    env_file:
      - .env.production
    environment:
      - PORT=4242
      - NODE_ENV=production
      - HOST=0.0.0.0
      # Stripe Config
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY:-}
      - VITE_STRIPE_PUBLISHABLE_KEY=${VITE_STRIPE_PUBLISHABLE_KEY:-}
      - VITE_STRIPE_MODE=live
      - VITE_USE_HTTPS=true
      # 添加 CORS 配置
      - ALLOWED_ORIGINS=https://love.saga4v.com
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4242/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    command: >
      sh -c "
        echo ' Starting Payment Service...' &&
        sleep 15 &&
        npm install &&
        npm start
      "
    restart: unless-stopped

networks:
  default:
    driver: bridge

volumes:
  payment_data:
    driver: local