# version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4173:4173"
    environment:
      - NODE_ENV=production
      - VITE_PAYMENT_URL=https://love.saga4v.com/api
      - VITE_SOCKET_URL=wss://love.saga4v.com
    networks:
      - app_network
    restart: unless-stopped

  payment-server:
    build:
      context: ./payment-server
      dockerfile: Dockerfile
    ports:
      - "4242:4242"
    environment:
      - NODE_ENV=production
      - SOCKET_URL=wss://love.saga4v.com
      - CORS_ORIGIN=https://love.saga4v.com
    env_file:
      - .env.production
    networks:
      - app_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-q", "-O", "/dev/null", "http://localhost:4242/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 90s

networks:
  app_network:
    name: app_network
    driver: bridge