# version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4173:4173"
    environment:
      - NODE_ENV=production
    networks:
      - app_network
    restart: unless-stopped

  payment-server:
    build:
      context: ./payment-server
      dockerfile: Dockerfile
    ports:
      - "4242:4242"
    environment:
      - NODE_ENV=production
    env_file:
      - .env.production
    networks:
      - app_network
    restart: unless-stopped

networks:
  app_network:
    name: app_network
    driver: bridge