FROM node:18-alpine

WORKDIR /app

RUN apk add --no-cache curl

COPY package*.json ./
RUN npm install --production

COPY . .
COPY .env.production .env
COPY .env.server .env.server

RUN apk add --no-cache curl

EXPOSE 4242

CMD ["node", "server/index.js"] 