version: '3'
services:
  # 前端服务
  frontend:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "4173:4173"  # Vite 生产预览端口
    env_file:
      - .env.production  # 使用生产环境配置文件
    environment:
      # AI API Keys
      - VITE_MOONSHOT_API_KEY=${VITE_MOONSHOT_API_KEY}
      - VITE_GEMINI_API_KEY=${VITE_GEMINI_API_KEY}
      # App Config
      - NODE_ENV=production
      - VITE_API_KEY=${VITE_API_KEY}
      - VITE_API_URL=http://payment:4242
      # Firebase Config
      - VITE_FIREBASE_API_KEY=${VITE_FIREBASE_API_KEY}
      - VITE_FIREBASE_AUTH_DOMAIN=${VITE_FIREBASE_AUTH_DOMAIN}
      - VITE_FIREBASE_PROJECT_ID=${VITE_FIREBASE_PROJECT_ID}
      - VITE_FIREBASE_STORAGE_BUCKET=${VITE_FIREBASE_STORAGE_BUCKET}
      - VITE_FIREBASE_MESSAGING_SENDER_ID=${VITE_FIREBASE_MESSAGING_SENDER_ID}
      - VITE_FIREBASE_APP_ID=${VITE_FIREBASE_APP_ID}
      - VITE_FIREBASE_MEASUREMENT_ID=${VITE_FIREBASE_MEASUREMENT_ID}
      # Stripe Config
      - VITE_STRIPE_PUBLISHABLE_KEY=${VITE_STRIPE_PUBLISHABLE_KEY}
      - VITE_STRIPE_MODE=${VITE_STRIPE_MODE}
      - HOST=0.0.0.0
    volumes:
      - ./src:/app/src:ro
      - ./public:/app/public:ro
      - ./vite.config.ts:/app/vite.config.ts:ro
    user: "node"
    command: >
      sh -c "
        echo '等待系统初始化...' &&
        sleep 10 &&
        echo '清理构建目录...' &&
        rm -rf dist/* &&
        echo '开始构建前端项目...' &&
        npm run build &&
        echo '构建完成，开始预览...' &&
        npm run preview --host 0.0.0.0
      "
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:4173"]
      interval: 60s
      timeout: 30s
      retries: 5
      start_period: 60s

  # 统一支付服务
  payment:
    build: 
      context: ./payment-server
      dockerfile: Dockerfile
    ports:
      - "4242:4242"
    env_file:
      - .env.production  # 使用生产环境配置文件
    environment:
      - PORT=4242
      # Stripe Config
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - VITE_STRIPE_PUBLISHABLE_KEY=${VITE_STRIPE_PUBLISHABLE_KEY}
      - VITE_STRIPE_MODE=${VITE_STRIPE_MODE}
      # PayPal Config
      # - VITE_PAYPAL_SANDBOX_MODE=${VITE_PAYPAL_SANDBOX_MODE}
      # - VITE_PAYPAL_CLIENT_ID=${VITE_PAYPAL_CLIENT_ID}
      # - VITE_PAYPAL_CLIENT_SECRET=${VITE_PAYPAL_CLIENT_SECRET}
      # - VITE_PAYPAL_API_URL=${VITE_PAYPAL_API_URL}
      - NODE_ENV=production
    depends_on:
      - frontend
    restart: unless-stopped

  # 注释掉 Telegram 支付服务，但保留配置供后续使用
  # telegram-payment:
  #   build:
  #     context: ./telegram-payment
  #     dockerfile: Dockerfile
  #   environment:
  #     - VITE_TELEGRAM_BOT_TOKEN=${VITE_TELEGRAM_BOT_TOKEN}
  #     - VITE_TELEGRAM_PAYMENT_PROVIDER_TOKEN=${VITE_TELEGRAM_PAYMENT_PROVIDER_TOKEN}
  #   depends_on:
  #     - payment
  #   restart: unless-stopped

networks:
  default:
    driver: bridge

volumes:
  payment_data:
    driver: local 