# version: '3.8'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt/live/love.saga4v.com/fullchain.pem:/etc/nginx/ssl/love/fullchain.pem:ro
      - /etc/letsencrypt/live/love.saga4v.com/privkey.pem:/etc/nginx/ssl/love/privkey.pem:ro
      - /etc/letsencrypt/live/play.saga4v.com/fullchain.pem:/etc/nginx/ssl/play/fullchain.pem:ro
      - /etc/letsencrypt/live/play.saga4v.com/privkey.pem:/etc/nginx/ssl/play/privkey.pem:ro
      - /var/www/certbot:/var/www/certbot:ro
    networks:
      - app_network
    restart: unless-stopped

networks:
  app_network: # When both Docker Compose files use driver: bridge for the same network name (app_network), Docker Compose will create a shared bridge network that allows containers from both compose files to communicate.
    # external: true  # 使用外部网络
    driver: bridge