FROM node:18-alpine

WORKDIR /app

RUN apk add --no-cache curl

COPY package*.json ./
RUN npm install --production

COPY . .
COPY .env.production .env
COPY .env.server .env.server

EXPOSE 4245

CMD ["node", "server/index.js"] 