version: '3'
services:
  # 前端服务
  frontend:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "4173:4173"  # Vite 生产预览端口
    environment:
      # AI API Keys
      - VITE_MOONSHOT_API_KEY=${VITE_MOONSHOT_API_KEY}
      - VITE_GEMINI_API_KEY=${VITE_GEMINI_API_KEY}
      # App Config
      - NODE_ENV=production
      - VITE_API_KEY=${VITE_API_KEY}
      - VITE_API_URL=http://payment:4242
      # Firebase Config
      - VITE_FIREBASE_API_KEY=${VITE_FIREBASE_API_KEY}
      - VITE_FIREBASE_AUTH_DOMAIN=${VITE_FIREBASE_AUTH_DOMAIN}
      - VITE_FIREBASE_PROJECT_ID=${VITE_FIREBASE_PROJECT_ID}
      - VITE_FIREBASE_STORAGE_BUCKET=${VITE_FIREBASE_STORAGE_BUCKET}
      - VITE_FIREBASE_MESSAGING_SENDER_ID=${VITE_FIREBASE_MESSAGING_SENDER_ID}
      - VITE_FIREBASE_APP_ID=${VITE_FIREBASE_APP_ID}
      - VITE_FIREBASE_MEASUREMENT_ID=${VITE_FIREBASE_MEASUREMENT_ID}
      - HOST=0.0.0.0
    volumes:
      - ./src:/app/src:ro
      - ./dist:/app/dist
      - ./public:/app/public:ro
    command: >
      sh -c "
        echo '开始构建前端项目...' &&
        npm run build &&
        echo '构建完成，开始预览...' &&
        npm run preview --host 0.0.0.0 --port 4173
      "
    restart: unless-stopped

  # 统一支付服务（处理 Stripe 和 PayPal）
  payment:
    build: 
      context: ./payment-server
      dockerfile: Dockerfile
    ports:
      - "4242:4242"
    environment:
      - PORT=4242
      # Stripe Config
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - VITE_STRIPE_PUBLISHABLE_KEY=${VITE_STRIPE_PUBLISHABLE_KEY}
      - VITE_STRIPE_MODE=${VITE_STRIPE_MODE}
      # PayPal Config
      - VITE_PAYPAL_SANDBOX_MODE=${VITE_PAYPAL_SANDBOX_MODE}
      - VITE_PAYPAL_CLIENT_ID=${VITE_PAYPAL_CLIENT_ID}
      - VITE_PAYPAL_CLIENT_SECRET=${VITE_PAYPAL_CLIENT_SECRET}
      - VITE_PAYPAL_API_URL=${VITE_PAYPAL_API_URL}
    depends_on:
      - frontend
    restart: unless-stopped

  # Telegram 支付服务
  telegram-payment:
    build:
      context: ./telegram-payment
      dockerfile: Dockerfile
    environment:
      - VITE_TELEGRAM_BOT_TOKEN=${VITE_TELEGRAM_BOT_TOKEN}
      - VITE_TELEGRAM_PAYMENT_PROVIDER_TOKEN=${VITE_TELEGRAM_PAYMENT_PROVIDER_TOKEN}
    depends_on:
      - payment
    restart: unless-stopped

networks:
  default:
    driver: bridge

volumes:
  payment_data:
    driver: local 