FROM nginx:latest

# Install curl for health checks
RUN apt-get update && apt-get install -y curl && rm -rf /var/lib/apt/lists/*

# Copy custom Nginx configuration
COPY nginx.global.250128.conf /etc/nginx/nginx.conf